parser: babel-eslint
extends:
  - airbnb-base
  - plugin:flowtype/recommended
plugins:
  - flowtype
  - jsdoc
  - chai-friendly
env:
  node: true
  mocha: true
rules:
  no-param-reassign: "off"
  import/extensions:
      - off
  import/no-unresolved:
    - error
    - commonjs: true
      ignore: [ ^aws-sdk$, aws-operations$, fs-operations$, connection$, ^./contrib/*, ^oracledb$, ^request-promise-native$ ]
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
      - 'src/tests/unit/**/*.js'
      - gulpfile.js
      - 'src/db/awsS3/aws-operations.js'
      - 'src/db/oracledb/connection.js'
  import/prefer-default-export: 'off'
  import/no-default-export:
    - error
  no-unused-expressions: 'off'
  chai-friendly/no-unused-expressions: 'error'
  jsdoc/require-param:
    - warn
    - exemptedBy: [ type ]
  jsdoc/require-returns:
    - warn
    - exemptedBy: [ type ]
  jsdoc/no-undefined-types:
    - warn
      # Express and gulpfile types
    - definedTypes:
        - RequestHandler
        - ErrorRequestHandler
        - Request
        - Response
        - Stream
        - ChildProcess
  jsdoc/require-jsdoc:
    - warn
    - publicOnly: true
      require:
        ArrowFunctionExpression: true
settings:
  import/resolver:
    babel-module: {}
